name = "AeroChat WhatsApp"
client_id ="3b12f68037d0fa4122ceacbfe3f4f1c0"
application_url = "http://localhost:3000"
embedded = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "http://localhost:3000/auth/callback"
]
[webhooks]
api_version = "2024-01"